name: Override Environment variables
on: push
env:
  EXAMPLE: Defined by workflow level # ワークフローレベルで環境変数を定義
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ env.EXAMPLE }}" # ワークフローレベルの環境変数を出力
      - env:
         EXAMPLE: Defined by step level # ステップレベルで環境変数を定義
        run: echo "${{ env.EXAMPLE }}" # ステップレベルの環境変数を出力

